TRANSACTION_STATUS = {
    'ACTIVE': 'ACTIVE',
    'BLOCKED': 'BLOCKED',
    'COMMITTED': 'COMMITTED',
    'ABORTED': 'ABORTED'
}

RESOURCE_STATUS = {
    'READ_LOCKED': 'READ_LOCKED',
    'WRITE_LOCKED': 'WRITE_LOCKED'
}